services:
  # Web Service (Flask App)
  - type: web
    name: agendarenta4
    env: python
    region: frankfurt  # Cambia a la región más cercana
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: agendarenta4-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USE_SSL
        value: False
      - key: MAIL_USERNAME
        sync: false  # Set manually in Render dashboard
      - key: MAIL_PASSWORD
        sync: false  # Set manually in Render dashboard
      - key: MAIL_DEFAULT_SENDER
        sync: false  # Set manually in Render dashboard
      - key: MAIL_DEBUG
        value: False

  # PostgreSQL Database
  - type: pserv
    name: agendarenta4-db
    env: docker
    plan: free
    region: frankfurt  # Debe ser la misma región que el web service
    ipAllowList: []  # Allow connections from anywhere (for migration)
